# Generated by Django 5.2.1 on 2025-06-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recipes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
